### ISSUE TITLE
unicode objects required for ipaddress 1.0.16

### ISSUE THREAD

**Issue by nuddelaug** [douganger/flask-ipfilter#1]
Hi with python2.7 and ipadress version 1.0.16 the code does not work as the ipaddress module expects unicode objects

  File "/usr/lib/python2.7/site-packages/ipaddress.py", line 163, in ip_address
    ' a unicode object?' % address)
AddressValueError: '127.0.0.1' does not appear to be an IPv4 or IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?

the attached  update to the whitelist module works as expected with your howto 
[flask-ipfilter-update.txt](https://github.com/douganger/flask-ipfilter/files/4904705/flask-ipfilter-update.txt)

**Comment by douganger** [comment]
Thank you for pointing that out and providing a fix. Would you like to submit a PR with the changes so you'll be listed as the author?

**Comment by nuddelaug** [comment]
as you want ... I dont need credits :)
